export enum AuthActionTypes {
    LOGIN_USER = '@@auth/LOGIN_USER',
    LOGIN_USER_SUCCESS = '@@auth/LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED = '@@auth/LOGIN_USER_FAILED',

    LOGOUT_USER = '@@auth/LOGOUT_USER',

    SIGNUP_USER = '@@auth/SIGNUP_USER',
    SIGNUP_USER_SUCCESS = '@@auth/SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILED = '@@auth/SIGNUP_USER_FAILED',

    SET_PASSWORD = '@@auth/SET_PASSWORD',

    FORGOT_PASSWORD = '@@auth/FORGOT_PASSWORD',
    FORGOT_PASSWORD_SUCCESS = '@@auth/FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILED = '@@auth/FORGOT_PASSWORD_FAILED',

    ACTIVATE_USER = '@@auth/ACTIVATE_USER',
    ACTIVATE_USER_SUCCESS = '@@auth/ACTIVATE_USER_SUCCESS',
    ACTIVATE_USER_FAILED = '@@auth/ACTIVATE_USER_FAILED',
}